### ISSUE TITLE
Incorrect descriptions/usage for shows and search arguments

### ISSUE THREAD

**Issue by DmitrySandalov** [juantascon/tvcmd#19]
tvcmd:> shows --help
usage: save [-h]

Save episodes status DB and cache

optional arguments:
  -h, --help  show this help message and exit

example: save

tvcmd:> search --help
usage: save [-h] SHOW

Save episodes status DB and cache

positional arguments:
  SHOW        show name or part, ex: the offi

optional arguments:
  -h, --help  show this help message and exit

example: search the offi

**Comment by juantascon** [comment]
fixed at https://github.com/juantascon/tvcmd/commit/57432d538704d526968f550ccd251a1b203a57a7

**Comment by DmitrySandalov** [comment]
The description and epilog messages for 'shows --help' are still the same.

```
tvcmd:> shows --help
usage: save [-h]

Save episodes status DB and cache

optional arguments:
  -h, --help  show this help message and exit

example: save
```

**Comment by juantascon** [comment]
you are right, I fixed search but missed save, I'll reopen the issue
